2021-05-27 23:12:23 [INFO at __init__ in client.py] Client program initiated
2021-05-27 23:12:24 [ERROR at Connect in client.py] Exception occured
Traceback (most recent call last):
  File "D:\Computer Network\weatherapp_class_project-master\client\client.py", line 108, in Connect
    self.sock.connect((host, port))
TypeError: an integer is required (got type str)
2021-05-27 23:12:24 [INFO at Connect in client.py] No connection established
2021-05-27 23:12:26 [ERROR at SendMessage in client.py] Counld not send message of length 35 to server.
Traceback (most recent call last):
  File "D:\Computer Network\weatherapp_class_project-master\client\client.py", line 309, in SendMessage
    bytes_sent = self.sock.send(message)
OSError: [WinError 10057] A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied
2021-05-27 23:12:32 [ERROR at SendMessage in client.py] Counld not send message of length 34 to server.
Traceback (most recent call last):
  File "D:\Computer Network\weatherapp_class_project-master\client\client.py", line 309, in SendMessage
    bytes_sent = self.sock.send(message)
OSError: [WinError 10057] A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied
2021-05-27 23:12:44 [ERROR at SendMessage in client.py] Counld not send message of length 34 to server.
Traceback (most recent call last):
  File "D:\Computer Network\weatherapp_class_project-master\client\client.py", line 309, in SendMessage
    bytes_sent = self.sock.send(message)
OSError: [WinError 10057] A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied
